language: python
python:
        - "3.6"
install:
        - pip install -r requirements.txt
before_script:
        - cp settings.py.example settings.py
script:
        - python -m unittest discover test/
after_success: coveralls
notifications:
        email:
                recipients:
                        - busioccostin@gmail.com
